### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by ltworf** [davidfstr/trycast#1]
your pypi page suggests MIT license, but here there is absolutely nothing. So legally it is not possible to use this library.

**Comment by davidfstr** [comment]
Thanks for reporting! I added a LICENSE.md file (which GitHub recognizes as MIT), which I'm guessing is what you were looking for.

**Comment by ltworf** [comment]
Yeah :)

Not that I have any intention of using this, since I already made https://github.com/ltworf/typedload/ but I was just taking a look

**Comment by davidfstr** [comment]
Yep I noticed you'd made the `typedload` library. ^_^ Looks useful, and is potentially a superset of what `trycast` is trying to do. Sadly I can't depend on it for my work projects due to the GPL license.

**Comment by ltworf** [comment]
Good luck then :)

Personally I don't care to make a library that might end up used in proprietary projects.
