### ISSUE TITLE
Confusing error message when arguments in trycast functions are swapped

### ISSUE THREAD

**Issue by rednafi** [davidfstr/trycast#7]
Consider the following MRE where within the print function, I've swapped the argument position in the `trycast` function:

```python
# script.py

from trycast import trycast
from typing import TypedDict


class Person(TypedDict):
    name: str
    age: float


p: Person = {"name": "mike", "age": 61.0}

print(trycast(p, Person))
```

Here, the first argument of the `trycast` function is the **object** (instead of the **type**) and the second argument is the **type** (instead of the **object**). It invokes the following error:

```python
Traceback (most recent call last):
  File "/home/rednafi/workspace/personal/demo/script.py", line 12, in <module>
    print(trycast(p, Person))
  File "/home/rednafi/workspace/personal/demo/.venv/lib/python3.9/site-packages/trycast.py", line 232, in trycast
    if isinstance(value, type):  # type: ignore
TypeError: isinstance() arg 2 must be a type or tuple of types
```

IMHO, this is a leaky abstraction and the error should be handled in a graceful manner.  To fix this, we can take some inspiration from the `typing.cast` function. If we swap the argument position in the `typing.cast` function, mypy throws the following error:

```python
# script.py
from typing import cast
from typing import TypedDict

class Person(TypedDict):
    name: str
    age: float


p : Person = {'name': "hello", "age": 11.0}

print(cast(p, Person))               # Notice we're using `typing.cast` instead of `trycast`
```

```
script.py:14: error: Variable "script.p" is not valid as a type
```

This error is concise and less confusing.

**Test Bench:**
Python Version: 3.9.5
Operating System: Ubuntu 20.04

**Comment by davidfstr** [comment]
Agreed that the error could be improved in this case.

I expect a challenge may be some difficulty in recognizing whether the first argument is actually a "valid type". Likely the implementation of `cast` could be consulted as a pointer.

I don't expect to have the bandwidth to make this improvement myself for the next few months, so I will welcome PRs from others in this area. :)

**Comment by rednafi** [comment]
I'm looking into the internals and will start working once I'm confident enough to make the changes. Thank you for your prompt response. Until then, let's keep this open.

**Comment by d-k-bo** [comment]
I think this can be fixed using `typing._type_check()`, which is used internally for things like `Optional`, eg.
```python
>>> a: Optional[p]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/typing.py", line 275, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.9/typing.py", line 352, in __getitem__
    return self._getitem(self, parameters)
  File "/usr/lib/python3.9/typing.py", line 475, in Optional
    arg = _type_check(parameters, f"{self} requires a single type.")
  File "/usr/lib/python3.9/typing.py", line 164, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: typing.Optional requires a single type. Got {'name': 'mike', 'age': 61.0}.
```

This check could be implemented with
```python
# (from typing import _type_check)

_type_check(tp, "trycast() requires a type as its first argument.")
```
which would throw
```python
TypeError: trycast() requires a type as its first argument. Got {'name': 'mike', 'age': 61.0}.
```
I wonder how you think about importing a "private" function in trycast.

**Comment by davidfstr** [comment]
> I wonder how you think about importing a "private" function in trycast.

It's not really a problem so long as there is test coverage. There's some additional maintenance burden if the function disappears or has an unstable implementation, but I don't think either of those will likely be the case for this function.
